version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:14.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
      KEYCLOAK_WELCOME_THEME: pac
      KEYCLOAK_DEFAULT_THEME: pac
    ports:
      - 8080:8080
    volumes:
      - ./theme/:/opt/keycloak/themes
    depends_on:
      - postgres
